version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    env_file:
      - database.env  
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase:4.33-alpine
    container_name: liquibase_cli
    depends_on:
      - mysql
    volumes:
      - ./changelogs:/liquibase/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
      - ./drivers:/liquibase/classpath
    entrypoint: tail -f /dev/null   # keep container running
