# https://taskfile.dev

version: '3'

tasks:
  start-server:
    cmds:
      - docker compose up --build -d
    desc: Start MySQL server + liquibase cli using Docker
  stop-server:
    cmds:
      - docker compose down
    desc: Stop MySQL server + liquibase cli Docker container
  generate-change-log:
    desc: Generate changelog from existing database + save to file
    cmds:
      - docker exec -it liquibase_cli liquibase generateChangeLog --changeLogFile=changelogs/generated-changelog.yaml
      - docker cp liquibase_cli:/liquibase/changelogs/generated-changelog.yaml ./changelogs/generated-changelog.yaml
      - echo "Changelog generated and copied to local changelogs/generated-changelog.yaml"
  sync-db:
    cmds:
      - docker exec -it liquibase_cli liquibase changelogSync
    desc: Sync database with changelog file without running migration
  migrate:
    cmds:
      - docker exec -it liquibase_cli liquibase update
    desc: Run database migration
  rollback:
    cmds:
      - docker exec -it liquibase_cli liquibase rollbackCount 1
    desc: Rollback last database migration
  status:
    cmds:
      - docker exec -it liquibase_cli liquibase status
    desc: Check database migration status
  history:
    cmds:
      - docker exec -it liquibase_cli liquibase history
    desc: Show database migration history
  clear:
    cmds:
      - docker exec -it liquibase_cli liquibase clearCheckSums
    desc: Clear database migration checksums